Repository ultralytics/replicate, pull requests merged in 2025-08, with the labels that each got.

#1 Initial Replicate implementation
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/workflows/ci.yml
  .github/workflows/push-all.yml
  .github/workflows/push.yml
  README.md
  custom/README.md
  custom/cog.yaml
  custom/predict.py
  docs/README.md
  export_models.py
  pyproject.toml
  requirements.txt
  template/README.md
  template/__init__.py
  template/module1.py
  test_prediction.py
  tests/README.md
  tests/test_with_pytest.py
  tests/test_with_unittest.py
  yolo11n/README.md
  yolo11n/cog.yaml
  yolo11n/predict.py
Labels: dependencies, documentation, enhancement

#4 Update README.md
  README.md
Labels: documentation

#2 Add windows-latest runners to ci.yml
  .github/workflows/ci.yml
  .github/workflows/push-all.yml
  .github/workflows/push.yml
Labels: enhancement

#5 Update push.yml
  .github/workflows/push.yml
Labels: enhancement

#3 Update push-all.yml
  .github/workflows/push-all.yml
  .github/workflows/push.yml
Labels: enhancement

#9 Add zidane.jpg example image
  .github/workflows/push.yml
  custom/cog.yaml
  custom/predict.py
  yolo11n/cog.yaml
  yolo11n/predict.py
Labels: documentation, enhancement

#11 Update push.yml
  .github/workflows/ci.yml
  .github/workflows/push.yml
  README.md
  assets/bus.jpg
  assets/zidane.jpg
  custom/README.md
  custom/cog.yaml
  custom/predict.py
  export_models.py
  test_prediction.py
  yolo11n/README.md
  yolo11n/cog.yaml
  yolo11n/predict.py
Labels: enhancement

#13 Add model URL https://replicate.com/ultralytics/yolo11n
  README.md
  yolo11n/README.md
  yolo11n/predict.py
Labels: documentation, enhancement

#14 Fix image output
  yolo11n/predict.py
Labels: enhancement

#15 Save annotation result to output.png
  yolo11n/predict.py
Labels: enhancement

#16 Output "media_path"
  yolo11n/predict.py
Labels: enhancement

#17 Directly return image
  yolo11n/predict.py
Labels: enhancement

#24 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/push.yml
  yolo11n/cog.yaml
  yoloe11s/cog.yaml
  yoloe11s/predict.py
  yolov8s-worldv2/cog.yaml
Labels: documentation, enhancement
